// recipes/angular/testing-components/src/main.ts
// this code is part of the simplux recipe "using simplux in my Angular application":
// https://github.com/MrWolfZ/simplux/tree/master/recipes/angular/using-in-angular-application

// required to be first here for code sandbox to work
import 'core-js/features/reflect'

import { enableProdMode } from '@angular/core'
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic'
import { AppModule } from './app/app.module'
import { environment } from './environments/environment'

if (environment.production) {
  enableProdMode()
}

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch(err => console.error(err))

// recipes/react/using-hot-module-reloading/src/index.tsx
// this code is part of the simplux recipe "using hot module reloading in my React application":
// https://github.com/MrWolfZ/simplux/tree/master/recipes/react/using-hot-module-reloading

import { SimpluxProvider } from '@simplux/react'
import React from 'react'
import { render } from 'react-dom'
import { Counter } from './counter'

const App = () => (
  <SimpluxProvider>
    <Counter />
  </SimpluxProvider>
)

render(<App />, document.getElementById('root'))
